name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/authorized_keys"
      - run: chmod 600 "$HOME/.ssh/authorized_keys"
      # Deploy
      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/authorized_keys -o StrictHostKeyChecking=no" --archive --compress --delete . u2223620@server223.hosting.reg.ru:/var/www/u2223620/data/www/sekkey.pkprograms.ru